version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:80"
    # For local development to rebuild quickly, you can comment build and use image if pushed
    # image: your-dockerhub-username/your-app:latest
    # environment: []