name: Frontend CI & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build the app
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: ./frontend
        env:
          GIT_USER: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_USER"
          REPO_URL=https://$GH_TOKEN@github.com/${{ github.repository }}.git
          npx gh-pages -d build -u 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>' -r $REPO_URL
